## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts

server.name: kibana
# Sets the name of the Kibana server instance. This name is 
# mainly for internal reference and does not affect functionality.


server.host: 0.0.0.0
# Configures Kibana to listen on all network interfaces. 
# This makes it accessible from outside the Docker container, 
# which is necessary if you want to access Kibana's web interface
# from other machines or services.


elasticsearch.hosts: [ http://elasticsearch:9200 ]
# Specifies the URL of the Elasticsearch instance that Kibana 
# will connect to. The example uses the hostname elasticsearch, 
# which assumes that the Elasticsearch container is accessible 
# on the Docker network with this hostname. You can adjust this
# depending on your Docker network configuration or Elasticsearch service URL.


monitoring.ui.container.elasticsearch.enabled: ${MONITORING_ELASTICSEARCH_IN_UI}
# monitoring.ui.container.logstash.enabled: true
# This setting is used to enable or disable monitoring features in Kibana's
# user interface. By using the ${MONITORING_ELASTICSEARCH_IN_UI} placeholder,
# you can dynamically configure this option based on your environment
# (e.g., enabled for production, disabled for development).


## X-Pack security credentials
elasticsearch.username: kibana_system
# Specifies the username that Kibana uses to connect to Elasticsearch. 
# The kibana_system user is a built-in user designed for Kibana to
# interact with Elasticsearch securely.


elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}
# Defines the password for the kibana_system user.
# Using ${KIBANA_SYSTEM_PASSWORD} allows you to set the
# password via an environment variable, which is more secure
# than hardcoding it into the configuration file.


elasticsearch.requestTimeout: ${ELASTIC_REQUEST_TIMEOUT}
# Sets the request timeout in milliseconds for queries
# sent from Kibana to Elasticsearch. The ${ELASTIC_REQUEST_TIMEOUT}
# placeholder can be replaced with a specific value based on your
# environment or requirements.


#xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.reporting.csv.maxSizeBytes: ${XPACK_REPORTING_CSV_MAX_SIZE_BYTES}
# Controls the maximum size, in bytes, of CSV files generated by
# Kibana’s reporting feature. The ${XPACK_REPORTING_CSV_MAX_SIZE_BYTES}
# placeholder allows this value to be set dynamically, helping manage
# the size of reports generated by users.
